---

- block:

    - name: initialize terraform
      shell: |
        terraform init {{ terraform.default_args }}
      args:
        chdir: "{{ role_context }}/files"
      register: init

    - debug: var=init

    - name: validate provisioning
      shell: |
        terraform plan \
          {{ terraform.default_args }} \
          -var aws_profile={{ aws_profile | default('default') }}
      register: provisioning_plan
      args:
        chdir: "{{ role_context }}/files"
      register: plan

    - debug: var=plan

    - name: apply state
      shell: |
        terraform apply \
          {{ terraform.default_args }} \
          -auto-approve \
          -var aws_profile={{ aws_profile | default('default') }}
      args:
        chdir: "{{ role_context }}/files"


