---

- block:

    - name: initialize terraform
      shell: terraform init
      args:
        chdir: "{{ role_context }}/files"
      register: init

    - debug: var=init

    - name: validate provisioning
      shell: terraform plan
      register: provisioning_plan
      args:
        chdir: "{{ role_context }}/files"
      register: plan

    - debug: var=plan

