---

- block:

    - name: initialize terraform
      shell: |
        terraform init {{ terraform.default_args }}
      register: provisioning_init
      args:
        chdir: "{{ role_context }}/files"

    - debug: var=provisioning_init

    - name: validate provisioning
      shell: |
        terraform plan \
          {{ terraform.default_args }} \
          -var aws_profile={{ aws_profile | default('default') }}
      register: provisioning_plan
      args:
        chdir: "{{ role_context }}/files"

    - debug: var=provisioning_plan

    - name: apply state
      shell: |
        terraform apply \
          {{ terraform.default_args }} \
          -auto-approve \
          -var aws_profile={{ aws_profile | default('default') }}
      register: provisioning_apply
      args:
        chdir: "{{ role_context }}/files"

    - debug: var=provisioning_apply


